# notes

- numpy provides storage efficiency, better way to handle data processing, it is fast
- help for dynamic memory allocation (no concept of pointers in python, but with help of numpy we can access pointers)

In [1]:
import numpy as np

myarr = np.array([3,2,8,9])
myarr

array([3, 2, 8, 9])

In [14]:
myarr = np.array([3,2,85225666,9], np.int8) # for memory management you can give size to int but if you store 
# more than the given space it displays false values
myarr

array([  3,   2, -62,   9], dtype=int8)

In [4]:
import numpy as np

myarr = np.array([[2,7,9,5],[3,2,8,9]])
print(myarr)

myarr[1,1]

print('shape',myarr.shape)
print('dtype',myarr.dtype) # the u11 dtype is for string

# to view in matrix form

import pandas as pd
myarr = np.array([[2,7,9,5],[3,2,8,9]])
df1 = pd.DataFrame(myarr)
df1

[[2 7 9 5]
 [3 2 8 9]]
shape (2, 4)
dtype int32


0  1  2  3
0  2  7  9  5
1  3  2  8  9

In [8]:
import numpy as np

myarr = np.array([[2,7,9,5],[3,'a',8,9]])
print(myarr)

myarr[1,1]

print('shape',myarr.shape)
print('dtype',myarr.dtype) # the u11 dtype is for string, it automatically assigns the dtype to whole array 
# if not given explicitly
print('\n the u11 dtype is for string, numpy automatically assigns the dtype to whole array if not given explicitly')
print('\n numpy assigns most complex elements dtype to whole array')
print('\n refer : https://danielmuellerkomorowska.com/tag/string/')

# to view in matrix form

import pandas as pd
myarr = np.array([[2,7,9,5],[3,'a',8,9]])
df1 = pd.DataFrame(myarr)
df1

[['2' '7' '9' '5']
 ['3' 'a' '8' '9']]
shape (2, 4)
dtype <U11

 the u11 dtype is for string, numpy automatically assigns the dtype to whole array if not given explicitly

 numpy assigns most complex elements dtype to whole array

 refer : https://danielmuellerkomorowska.com/tag/string/


0  1  2  3
0  2  7  9  5
1  3  a  8  9

In [15]:
# assigning dtype explicitly

arr = np.array([3,2,1])
print(arr.dtype)

arr = np.array([3,2,1], dtype=object) # assigning dtype explicitly
print(arr.dtype)

int32
object


In [47]:
import numpy as np

myarr = np.array([[2,7,623],[3,2,8,9]]) # if the size of internal array is not equal it considers it as array of list
print(myarr)

print('shape',myarr.shape)

# to view in matrix form

import pandas as pd
myarr = np.array([[2,7,623],[3,2,8,9]])
df1 = pd.DataFrame(myarr)
df1

[list([2, 7, 623]) list([3, 2, 8, 9])]
shape (2,)


C:\Users\PC\AppData\Local\Temp\ipykernel_9884\868813042.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  myarr = np.array([[2,7,623],[3,2,8,9]]) # if the size of internal array is not equal it considers it as array of list
C:\Users\PC\AppData\Local\Temp\ipykernel_9884\868813042.py:11: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  myarr = np.array([[2,7,623],[3,2,8,9]])


0
0   [2, 7, 623]
1  [3, 2, 8, 9]

In [56]:
myarr = np.array([[2,7,9,5],[3,2,8,9]])
print('before : \n',myarr)

myarr[1,1] = 4 # modify element of an array

print('after : \n',myarr)

before : 
 [[2 7 9 5]
 [3 2 8 9]]
after : 
 [[2 7 9 5]
 [3 4 8 9]]


## 5 general array creation methods:

#### conversion from other python structures

In [58]:
listarray = np.array([[2,7,9,2],[8,4,7,6]])
print(listarray)
print(listarray.dtype)

[[2 7 9 2]
 [8 4 7 6]]
int32


In [60]:
np.array({25,78,14}) # notice that dtype is object which is not efficient, always prefer to use array

array({25, 78, 14}, dtype=object)

#### intrinsic numpy array creation objects

- np.zeros

In [61]:
zeros = np.zeros(([2,5])) # returns array of floating zeros of given shape
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

- np.arange()

In [62]:
rng = np.arange(10) # creates array of specified range(n-1)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
print("A\n", np.arange(4).reshape(2, 2), "\n") # 2d array
print("A\n", np.arange(4, 10), "\n")
print("A\n", np.arange(4, 20, 3), "\n")

A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 



- np.linspace(start, end, array_length)

In [67]:
# end - start = ans, then ans / (array_length-1)
# 3-2 = 1, 1 / 4 = 0.25, hence 2,2.25,2.5,2.75,3
lnspc = np.linspace(2,3,5)
lnspc

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

- np.empty()

In [17]:
emp = np.empty((4,6)) # inputs random values for a given array shape
emp

array([[4.73517493e-120, 7.76435379e+217, 1.71872056e+161,
        8.82142681e+199, 6.32300954e+233, 1.96101067e+243],
       [9.47069335e-154, 1.91315233e-070, 1.27921601e-152,
        3.59363102e+246, 1.76540132e+137, 1.05855590e+200],
       [2.04747568e+161, 1.67494831e+243, 3.65299313e+233,
        6.01124019e+175, 6.38182106e+175, 2.20132030e-152],
       [1.96088859e+243, 6.32192024e-043, 2.64218506e-061,
        2.71743166e-033, 1.01388782e-070, 3.54662380e+160]])

In [79]:
emp_like = np.empty_like(lnspc) # helps create a similar shape array which we pass in argument 
emp_like

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

- np.indentity()

In [83]:
ide = np.identity(10)
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

- reshape() and ravel() functions

In [100]:
arr = np.arange(99)
print(arr.shape)
arr

(99,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [106]:
arr = arr.reshape(3,33)
print(arr)
print('shape of array : ',arr.shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]
shape of array :  (3, 33)


In [102]:
arr.reshape(3,31) # not allowed because 3*31 = 93 which is not equal to length of arr

ValueError: cannot reshape array of size 99 into shape (3,31)

In [104]:
arr = arr.ravel() # to convert back to 1d array
print(arr.shape)
arr

(99,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# numpy axis